-- Migration: add confidence columns to parts and parts_catalog with IF NOT EXISTS
ALTER TABLE parts ADD COLUMN IF NOT EXISTS confidence NUMERIC DEFAULT 1.0 NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'seed' NOT NULL;
ALTER TABLE parts ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE parts_catalog ADD COLUMN IF NOT EXISTS confidence NUMERIC DEFAULT 1.0 NOT NULL;
ALTER TABLE parts_catalog ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'seed' NOT NULL;
ALTER TABLE parts_catalog ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMP WITH TIME ZONE;
